services:
  tooling_frontend:
    build: 
      context: ./app
    ports:
      - "5000:80"
    volumes:
      - tooling_frontend:/var/www/html  # Named volume for frontend
        #    networks:
        #- tooling-network
    container_name: tooling-cont
    restart: on-failure
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
      #networks:
      #- tooling-network
    container_name: toolingdb
    environment:
      - MYSQL_DATABASE=${MYSQL_DBNAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASS}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql  # Named volume for database data
      - ./tooling_db_schema.sql:/docker-entrypoint-initdb.d/tooling_db_schema.sql  # Mount schema directory

        #networks:
        #tooling-network:
        # driver: bridge

volumes:
  tooling_frontend:
  db:

